import 'package:flutter/cupertino.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class AppConstants {
  static final ltrPadding = EdgeInsets.symmetric(horizontal: 20.w);

  static const companyIntro =
      'This company was founded by Mr. Rico Tee, a registered nurse by profession with previous experience both in NHS and the private sector.As a nurse, he saw and experienced short staffing of facilities, a common problem in the health care sector which eventually leads to other problems such as:Quality of care.High costs to cover shifts.And other internal issues that affect consumers and providers alike.In order to solve this problem, the founder came up with an idea for companies to maximize their recruitment capability, and for qualified applicants to increase their visibility to potential employers.MAGNIJOBS’ target market is not only the health care sector in the UK but also other professions in different countries.\n';

  static const companyGoals =
      "The company’s App will be the one-stop shop for any applicant when it comes to finding a job. Magnijobs will revolutionize job-hunting by allowing employers and applicants to find each other quickly and efficiently. In addition, it will allow employers to find the most qualified candidates and for applicants to find positions that best fit their skills and experiences. The Magnijobs App will prove to be an important part of the development and evolution of the workforce and the recruitment experience";

  static const employerRecruitmentPlacement =
      "Employers, recruitment agencies, and placement agencies worldwide will be able to use the app, thus costing the companies less and giving them the ability focus on recruitment. MAGNIJOBS will give companies easy access to qualified candidates, thus making it easier to hire the best candidates.Companies that use MAGNIJOBS will have no problem finding top-quality staff. MAGNIJOBS offers a video showing potential clients how to navigate the App and start finding staff.";

  static const companyDiscalmir =
      '''*Disclaimer for Website:* All information on this website is published in good faith and for general information purposes only. The information provided on this website is “as is”, and MAGNIJOBS does not make any warranties about its completeness, reliability, and accuracy. Any action you take upon the information you find on this website is strictly at your own risk, and MAGNIJOBS will not be liable for any losses and or damages in connection with the use of this website.

*No Liability:* We disclaim any liability for any misrepresentations or misunderstandings between the parties during the hiring period. The app serves as a medium where the company’s clients hire candidates through accessing the candidates’ profile. We do pre-checks and verifications, but we do not assume any liability for any errors that may occur.

*No Refunds:* All clients of MAGNIJOBS must pay a monthly subscription fee for every service rendered by the App. We do not offer refunds of any kind for the services purchased by our clients.

*Fair Use Notice:* This site contains copyrighted material, the use of which has not always been specifically authorized by the copyright owner. We are making such material available for the benefit of our clients and applicants. We believe this constitutes a fair use of any such copyrighted material according to all applicable laws. If you wish to use copyrighted material from this site for the purposes of your own that go beyond fair use, you must obtain permission from the copyright owner.

*Copyright Notice:* Copyright 2021, MAGNIJOBS, registered to MAGNIJOBS PLATFORM LIMITED, Company Number NI678611. Trademark registration in progress at this time. Trademark Number UK00003731106.

*Terms and Conditions:* Your submission of information, including personal information, is governed by the terms of our privacy policy as updated from time to time, and any additional privacy notice issued by your employer.
We grant you a non-exclusive, non-transferable, non-sublicensable, personal, limited, revocable license to use the App for the purpose of gaining employment with one of our clients. Any other use of the App is strictly prohibited. We reserve all rights in and to the App, and we reserve the right to revoke this license at any time, in our sole discretion. 
You may nor rent, lease, sub-license, or translate the App in any way, and may not make any alterations to or modifications of the whole or any part of the App, or permit the App or any part if it is to be combined with or become incorporated in, any other programs.
You agree not to use the App in any unlawful manner, for any unlawful, or criminal purpose, or in any manner inconsistent with these terms, and not to use the App to record, post, or transmit any information that is defamatory, threatening, abusive, offensive, obscene, indecent, discriminatory, or otherwise objectionable. You also agree not to use the App in any way that could damage, impair, or compromise our systems or security or interfere with other users, or restrict or inhibit any other users from using the App, and you agree not to collect or harvest any information or data from the App or its systems, including, without limitation, by using any robot, spider, or other manual or automatic device to retrieve, index, “scrape”, “data mine”, or in any way father App content without our prior written consent.

*You acknowledge that:* (i) all intellectual property rights in and to the App belong to MAGNIJOBS PLATFORM LIMITED, or their licensors, (ii) the rights granted herein are licensed (not sold) to you, and (iii) you have no rights in, or to, the App or its content other than the right to use the App in accordance with these Terms.
All trademarks, service marks, trade names, and logos are proprietary to MAGNIJOBS  PLATFORM LIMITED, or used by it with the permission of its third-party providers. Nothing contained in this App should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any trademark displayed on this website without our written permission. 
We reserve the right, temporarily or permanently, in whole or in part, to modify, suspend, or discontinue the App without any notice for any reason without liability to you, except where prohibited by applicable law. You also acknowledge that the App is provided over the Internet and mobile networks and thus the quality and availability of the App may be affected by factors beyond our reasonable control. Therefore, we do not accept any responsibility for connectivity issues that you may experience when using the App.
You agree to indemnify us for any claims, actions, demands, losses, liabilities, damages, costs, and expenses (including legal expenses and other costs, such as attorneys’ fees) reasonably incurred by us that arise out of your use of the App in breach of these Terms. 
We reserve the right to discontinue, suspend, or modify the App at any time without notice and may block, terminate, or suspend your access to the App at any time without notice for any reason in our sole discretion, even if access continues to be allowed to others. Upon termination, you must cease use of the App and remove it from all applicable devices. 
To the extent permitted by applicable law, these Terms are governed and construed according to the laws of the United Kingdom, and you consent to the non-exclusive jurisdiction of the courts of the United Kingdom.

*Subscription Policy:* The subscriptions are on a monthly basis. All users must pay the monthly fee in order to have access to the App, and will receive a notice to renew their subscription. All users must have a subscription in good standing to begin the candidate recruitment process.   

*Recruitment Process:* The client agrees that it will not attempt to contact any applicants outside of the App and will not ask for any contact information from the candidate(s). The client agrees that it will request the applicant for any and all documentation and references and that it will contact the candidate to set up an interview through the App. 

''';

  static var applicatntDisclamir =
      '''*Disclaimer for Website:* All information on this website is published in good faith and for general information purposes only. The information provided on this website is “as is”, and MAGNIJOBS does not make any warranties about its completeness, reliability, and accuracy. Any action you take upon the information you find on this website is strictly at your own risk, and MAGNIJOBS will not be liable for any losses and or damages in connection with the use of this website.
MAGNIJOBS does not guarantee that the applicant will receive a job offer upon signing up with the app. All decisions are made based on the employer’s preference, the applicant’s resume, and the results of the interview. 

*Third Party websites:* The applicant agrees to share his or her information with third parties such as employers, agencies, and other recruiting institutions upon signing up with the MAGNIJOBS app. 

*No Liability:* We disclaim any liability for any misrepresentations or misunderstandings between the parties during the hiring period. The app serves as a medium where the company’s clients hire candidates through accessing the candidates’ profile. We do pre-checks and verifications, but we do not assume any liability for any errors that may occur.
Access to Personal Information: The candidate agrees that he or she will allow the client to access his or her references after the interview, and the applicant agrees to allow the client to access all other personal information at the request of the client in order to proceed to the final steps of the recruitment process. The parties agree that the client shall not attempt to contact the applicant outside of the App, and that neither party shall send or inquire about any contact information for the safety of both the client and the applicant. 

*Third Party Links:* We provide hyperlinks to external sites on our website. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a dead link. 
Please also be aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies for these sites as well as their “Terms of Service” before engaging in any business or uploading any information. 

*Applicant Profile:* All applicant profiles on the App have available and non-available designations, and Applicant shall have the right to change the availability status of his or her profile on the App if he or she accepts a job offer through the App.

*Fair Use Notice:* This site contains copyrighted material, the use of which has not always been specifically authorized by the copyright owner. We are making such material available for the benefit of our clients and applicants. We believe this constitutes a fair use of any such copyrighted material according to all applicable laws. If you wish to use copyrighted material from this site for the purposes of your own that go beyond fair use, you must obtain permission from the copyright owner. 

*Copyright Notice:* Copyright 2021, MAGNIJOBS, registered to MAGNIJOBS PLATFORM LIMITED, Company Number NI678611. Trademark registration in progress at this time. Trademark Number UK00003731106.

*Terms and Conditions:* Your submission of information, including personal information, is governed by the terms of our privacy policy as updated from time to time, and any additional privacy notice issued by your employer.
We grant you a non-exclusive, non-transferable, non-sublicensable, personal, limited, revocable license to use the App for the purpose of gaining employment with one of our clients. Any other use of the App is strictly prohibited. We reserve all rights in and to the App, and we reserve the right to revoke this license at any time, in our sole discretion. 
You may nor rent, lease, sub-license, or translate the App in any way, and may not make any alterations to or modifications of the whole or any part of the App, or permit the App or any part if it to be combined with or become incorporated in, any other programs.
You agree not to use the App in any unlawful manner, for any unlawful, or criminal purpose, or in any manner inconsistent with these terms, and not to use the App to record, post, or transmit any information that is defamatory, threatening, abusive, offensive, obscene, indecent, discriminatory, or otherwise objectionable. You also agree not to use the App in any way that could damage, impair, or compromise our systems or security or interfere with other users, or restrict or inhibit any other users from using the App, and you agree not to collect or harvest any information or data from the App or its systems, including, without limitation, by using any robot, spider, or other manual or automatic device to retrieve, index, “scrape”, “data mine”, or in any way father App content without our prior written consent.
You acknowledge that: (i) all intellectual property rights in and to the App belong to MAGNIJOBS PLATFORM LIMITED, or their licensors, (ii) the rights granted herein are licensed (not sold) toy you, and (iii) you have no rights in, or to, the App or its content other than the right to use the App in accordance with these Terms.
All trademarks, service marks, trade names, and logos are proprietary to MAGNIJOBS PLATFORM LIMITED, or used by it with the permission of its third-party providers. Nothing contained in this App should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any trademark displayed on this website without our written permission. 
We reserve the right, temporarily or permanently, in whole or in part, to modify, suspend, or discontinue the App without any notice for any reason without liability to you, except where prohibited by applicable law. You also acknowledge that the App is provided over the Internet and mobile networks and thus the quality and availability of the App may be affected by factors beyond our reasonable control. Therefore, we do not accept any responsibility for connectivity issues that you may experience when using the App.
You agree to indemnify us for any claims, actions, demands, losses, liabilities, damages, costs, and expenses (including legal expenses and other costs, such as attorneys’ fees) reasonably incurred by us that arise out of your use of the App in breach of these Terms. 
We reserve the right to discontinue, suspend, or modify the App at any time without notice and may block, terminate, or suspend your access to the App at any time without notice for any reason in our sole discretion, even if access continues to be allowed to others. Upon termination, you must cease use of the App and remove it from all applicable devices. 
To the extent permitted by applicable law, these Terms are governed and construed according to the laws of the United Kingdom, and you consent to the non-exclusive jurisdiction of the courts of the United Kingdom. 

*Non-Disclosure:* The candidate agrees not to disclose any confidential information of the company’s clients, including but not limited to, customer information, intellectual property, marketing and development information, business operations, product information, production processes, service information, proprietary computer code, computer technology, and accounting information, to any third party without the client’s prior written consent. The candidate agrees that any disclosure of the confidential information in breach of this agreement cannot reasonably or adequately be compensated for in money damages and that the client may be entitled to an injunction restraining the candidate from engaging or committing any such act. The candidate agrees to return any or all documents, disks, or other material in his or her possession that may contain the client’s confidential information to the client upon termination of employment.

*Required Signatures:* All applicants must sign a third-party access agreement, a confidentiality agreement, and an agreement letter. Applicants attending the free English test offered by MAGNIJOBS must sign a non-disclosure agreement. All tutors of the English exam must sign a non-disclosure agreement as well.

*Consent:* By using our website, you hereby consent to our disclaimer and agree to its terms.

*Update:* Should we update, amend, or make any changes to this document, those changes will be prominently posted here. 

''';

  static var tutorDisclamir =
      '''All tutors for the English exam must provide at least 4 1-hour lessons a week, focusing on writing, reading, listening, and speaking exams. These lessons may be provided at any time during the week. All tutors must commit to providing these lessons before they may access the App. 

We do not guarantee, represent, or warrant that your use of our service will be uninterrupted, timely, secure, or error-free. We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable. You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you. You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided ‘as is’ and ‘as available’ for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement. 

In no case shall MAGNIJOBS PLATFORM LIMITED, our directors, officers, employees, affiliates, endorsers, formulators, content contributors, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.

''';
}
